name: Update Blog Posts To Profile
on:
  schedule:
    # Runs daily at 12am
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGPOSTS"
          feed_list: "https://hash.brightshinycode.com/rss.xml"
          template: "$newline - $randomEmoji(💯,🔥,💫,🚀,🌮) [$title]($url)"
          commit_message: "Recent posts updated"
          max_post_count: 5
          date_format: shortDate
